Feature/000 add interfaces
thermeon/gocui pull request #2
Opened 2018-05-17 12:45 UTC by mgazza

gocui is lacking abstraction making it very hard to test code that consumes it directly. 
This change adds two interfaces over gocui to enable testing

2018-05-17 12:54 UTC, mgazza commented
Apologies for the naming of the interfaces. I wanted to make it easy to identify and therefore refactor in consuming code. If you can suggest better alternatives please do :)

2018-05-17 16:32 UTC, damastes requested changes

2018-05-17 16:32 UTC, damastes commented on gui.go
> +	//v.BgColor, v.FgColor = g.BgColor, g.FgColor
remove commented old code

2018-05-17 16:32 UTC, damastes commented on gui.go
> +func (g *Gui) SetKeybinding(viewname string, key interface{}, mod Modifier, handler func(Guier, Viewer) error) error {
Guier is a poop name

2018-05-17 16:32 UTC, damastes commented on gui.go
> +		if v.Name() == name {
Maps exist

2018-05-18 06:54 UTC, mgazza commented on gui.go
> +		if v.Name() == name {
yea was tempted to change this. it appears whoever wrote this didn't

2018-05-18 06:56 UTC, mgazza commented on gui.go
> +func (g *Gui) SetKeybinding(viewname string, key interface{}, mod Modifier, handler func(Guier, Viewer) error) error {
indeed; it is in keeping with go interface naming, i.e. reader, writer. I'd like to keep it upstream mergeable so I'm open to suggestions for the interface names

2018-05-18 07:19 UTC, damastes approved these changes

2018-05-21 16:34 UTC, skldt approved these changes
Nice :) About the naming though, I think it's okay to move away from Go's convention of naming interfaces here.

Maybe `Viewer -> Widget`? And `Guier -> Application`?

2018-05-30 09:39 UTC, mgazza commented
Going to keep the terrible interface names at present and just get this in. IMO view and gui should be renamed as well as the interfaces as they are also non-descriptive of what they do.

2018-05-30 09:39 UTC, merged